### ISSUE TITLE
Giving user feedback when item is successfully added

### ISSUE THREAD

**Issue by kkatoch89** [the-collab-lab/tcl-22-smart-shopping-list#24]
It would be nice for the user to get some visual feedback for when shopping item is successfully added. 
See below on wireframe:
![add-item](https://user-images.githubusercontent.com/40097537/115146689-8d500d80-a025-11eb-9d26-7a52f2f95930.png)

**Comment by dp46504** [comment]
I can take it ;)

**Comment by luisaugusto** [comment]
Hey @kkatoch89, just as a suggestion, since issue #7 also relates to creating alerts and we have already started thinking about UI, it might be a good idea to create some sort of snackbar alert similar to [material UI](https://material-ui.com/components/snackbars/) or [Notistack](https://github.com/iamhosseindhv/notistack) that can be reused. Those are just examples you can reference, I'd probably suggest Notistack since it's lightweight but building a snackbar from scratch would be good React practice if you have the time 😄

**Comment by kkatoch89** [comment]
Hey @luisaugusto! Thanks for pointing that out, you just saved us a lot of trouble if we had picked a different design/theme for the feedback compared to issue #7. Cool suggestions as well! Love the look of Notistack!

**Comment by dariatsvetkova** [comment]
@kkatoch89 I personally don't mind Notistack, as long as we can customize it down the road to make it look good with the design that we'll land on.

**Comment by cafloyd** [comment]
@kkatoch89 I haven't used Notistack before, but it looks great! I've used React Toast Notifications before, and I imagine it's similar implementation
